name: Release Next
on:
  push:
    branches:
      - next
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "info@networkteam.com"
      - run: npm version prerelease --preid=${{ steps.vars.outputs.sha_short }}
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
